#
# Comma Delimited INI file, ignore any line beginning with # as it is a comment
# but may help in understanding the coding structure:
#
# Col 1:  Ignore, it is just a Sequence Number for human quick reference to the various 386 Table XMTOUTFL fields
# Col 2:  Target Table XMTOUTFL attribute to populate      - Attribute - Field Name 
# Col 3:  Key Name Reference for Source of the Data that is to be populated into XMTOUTFL
          TSTAMP   - Col 4 contains a Mask for a Time Stamp YYYY-MM-DD:HH:MM:SS.mmmm
          DRCONV   - Col 4 contains a Date field in format DDMMMYY/hhmm [e.g. 28MAR25/1130] and needs to convert to YYYYMMDD.hhmm00 
          INIT     - Col 4 contains an actual value to use  
          DR       - Col 4 contains the 3 char IMF Label of data coming from the 4K DR IMF string eg /BCY = "BCY" 
          PFVAR    - Col 4 contains the label of the attribute containing the entire DR 4K string i.e. DR used to set SY_VARSTR   
          CFG2     - Col 4 data coming from Table XMTCFG2 - XMT_C1KEY in Table XMTCFG1 to get to XMTCFG2 XMT_C2KEY to map to XMTOUTFL SY2_DESTID
          IGNORE   - Ignore this attribute - dont populate 
          PFHDR    - Col 4 Data coming from Table PFWIZREZ Header Section i.e. non-DR
          CONCAT   - Col 4 contains valid Field names and constants to be concatonated - only one currently is OUTFTXD45 
# Col 4:  Contents highly dependent on Col 3 instruction
# Col 5:  Ignore, part of DSPFFD reference from XMTOUTFL  - Attribute - Data Type 
# Col 6:  Ignore, part of DSPFFD reference from XMTOUTFL  - Attribute - Field Length
# Col 7:  Ignore, part of DSPFFD reference from XMTOUTFL  - Attribute - Buffer Length 
# Col 8:  Ignore, part of DSPFFD reference from XMTOUTFL  - Attribute - Buffer Position
# Col 9:  Ignore, part of DSPFFD reference from XMTOUTFL  - Attribute - Field Usage 
# Col 10: Ignore, part of DSPFFD reference from XMTOUTFL  - Attribute - Column Heading (Blank in all these cases)  
#
SECTION-A: MAP-TO-XMTOUTFL
1,	OUT_RID,	INIT,	OUT,				char	3	NULL	NULL	YES
2,	OUT_STRUCT,	INIT,	001,				char	3	NULL	NULL	YES
3,	OUT_DATE,	PFHDR,	INDATE,				char	8	NULL	NULL	YES
4,	OUT_TIME,	PFHDR,	IHTIME,				char	6	NULL	NULL	YES
5,	OUT_ERRCOD,	IGNORE,	, 				char	2	NULL	NULL	YES
6,	OUT_STATUS,	IGNORE,	, 				char	1	NULL	NULL	YES
7,	OUT_TXD,	PFHDR,	WHDATE				char	8	NULL	NULL	YES
8,	OUT_LOCN8,	PFHDR,	IHSNDL,				char	8	NULL	NULL	YES
9,	OUT_LOCN,	PFHDR,	IHSNDL,				char	5	NULL	NULL	YES
10,	OUT_DATPIN,	TSTAMP, YYYY-MM-DD:HH:MM:SS.mmmm,  	char	26	NULL	NULL	YES
11,	OUT_DUPCNT,	IGNORE,	, 				decimal	NULL	1	0	YES
12,	OUT_FACK,	IGNORE,	, 				char	1	NULL	NULL	YES
13,	OUT_FREASN,	IGNORE,	, 				char	2	NULL	NULL	YES
14,	OUT_FSCNT,	IGNORE,	, 				decimal	NULL	2	0	YES
15,	OUT_FSTIME,	IGNORE,	, 				char	26	NULL	NULL	YES
16,	OUT_FATIME,	TSTAMP, YYYY-MM-DD:HH:MM:SS.mmmm,	char	26	NULL	NULL	YES
#17,	OUT_ORIGIN,	TSTAMP, YYYY-MM-DD:HH:MM:SS.mmmm,	char	10	NULL	NULL	YES
18,	OUT_ORIGSY,	IGNORE,	, 				char	7	NULL	NULL	YES
19,	OUT_BCKRCV,	IGNORE,	, 				char	1	NULL	NULL	YES
20,	OUT_BCK_SC,	IGNORE,	, 				char	2	NULL	NULL	YES
21,	OUT_FREESP,	IGNORE,	, 				char	2	NULL	NULL	YES
22,	OUTRTYP20,	INIT,	20,				char	2	NULL	NULL	YES
23,	OUTACT20,	DR,	ACT,				char	3	NULL	NULL	YES
24,	OUTCNF20,	DR,	CNF,				char	11	NULL	NULL	YES
25,	OUTNAM20,	DR,	NAM,				char	30	NULL	NULL	YES
26,	OUTPUL3C,	DR,	PUL,				char	3	NULL	NULL	YES
27,	OUTCTO20,	DR,	CTO,				char	5	NULL	NULL	YES
28,	OUTCHN20,	DR,	CHN,				char	2	NULL	NULL	YES
29,	OUTPUD20,	DR,	PUD,				char	12	NULL	NULL	YES
30,	OUTDOL3C,	DR,	DOL,				char	3	NULL	NULL	YES
31,	OUTCTI20,	DR,	CTI,				char	5	NULL	NULL	YES
32,	OUTDOD20,	DR,	DOD,				char	12	NULL	NULL	YES
33,	OUTCAR1C,	DR,	CAR,				char	1	NULL	NULL	YES
34,	OUTVTP20,	DR,	VTP,				char	4	NULL	NULL	YES
35,	OUTBCD20,	DR,	BCD,				char	7	NULL	NULL	YES
36,	OUTFLT20,	DR,	FLT,				char	6	NULL	NULL	YES
37,	OUTCID20,	DR,	CID,				char	24	NULL	NULL	YES
38,	OUTCCE20,	DR,	CCE,				char	4	NULL	NULL	YES
39,	OUTMOP20,	DR,	MOP,				char	2	NULL	NULL	YES
40,	OUTSOR20,	DR,	SOR,				char	22	NULL	NULL	YES
41,	OUTCON20,	DR,	CON,				char	31	NULL	NULL	YES
42,	OUTEQP20,	DR,	EQP				char	27	NULL	NULL	YES
43,	OUTRMK20,	DR,	RMK,				char	25	NULL	NULL	YES
44,	OUTBDT20,	DR,	BDT,				char	12	NULL	NULL	YES
45,	OUTSTN3C,	DR,	STN,				char	3	NULL	NULL	YES
46,	OUTBCY20,	DR,	BCY,				char	5	NULL	NULL	YES
321,	OUT_VARTYP,	INIT,	I,				char	1	NULL	NULL	YES
322,	OUT_VARSTR,	DR,	DR,				varchar	4096	NULL	NULL	YES
380,	SY2_DESTID,	CFG2,	XMT_C2KEY,			char	10	NULL	NULL	YES
381,	SY2_TMSAVE,	TSTAMP, YYYY-MM-DD:HH:MM:SS.mmmm,	datetime2	NULL	NULL	NULL	YES
382,	SY2_TMRECV,	TSTAMP, YYYY-MM-DD:HH:MM:SS.mmmm,	datetime2	NULL	NULL	NULL	YES
# SY2_STATUS: This is part of the WHERE CLAUSE used by XmtFio, it may be the entire WHERE CLAUSE operating on XMTOUTFL or a VIEW over XMTOUTFL 
383,	SY2_STATUS,	INIT,   N,		 	        char	1	NULL	NULL	YES
384,	SY2_STCODE,	INIT,   00,				char	2	NULL	NULL	YES
# 385,	OUT_DATA,	INIT, 0,				varbinary	40	NULL	NULL	YES 
100,    OUTFTXD45,      CONCAT, WHDATE!!"."!!IHTIME, 
101,    OUTFPUD45,      DRCONV,PUD,
102,    OUTFDOD45,      DRCONV,DOD,

# OUT_ACTION??? set defaulting to 'N'


SECTION-B: MAP-TO-XMTSTATS
1,      XMT_SRID,          INIT, STATS,,
2,      XMT_SCNF,          DR,   CNF,,
3,      XMT_STXD,          DR,   TXD,,
4,      XMT_SSEQ,          INIT,  0001,SEQ,   CLARIFICATION: SEQ indicats this is a Sequence number; if 001 is taken move to 002; etc.
5,      XMT_DCNT           INIT, 1,,   
6,      XMT_STDEST,        CFG2, XMT_C2KEY,,
7,      XMT_SHSEQ,         INIT, 01,,     
8,      XMT_SSCNT,         INIT, 01,,
9,      XMT_SSTIME,        DATE, YYYY-MM-DD:HH:MM:SS.mmmm, ,
10,     XMT_SFACK,         INIT,  ,
11,     XMT_SREASN,        INIT,  ,
12,     XMT_SATIME,        DATE,  YYYY-MM-DD:HH:MM:SS.mmmm, ,
13,     XMT_XMLSTR,        DR,DR, , ,    # Only the first n bytes                   